name: Format

on: [push]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Ruff formatting
        uses: astral-sh/ruff-action@v4.1.0
        with:
          args: format --check
          version-file: uv.lock

      - name: Check Ruff linting
        uses: astral-sh/ruff-action@v4.1.0
        with:
          args: check
          version-file: uv.lock
